# -*- coding: utf-8 -*-
"""Lab2-Task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5dvI2SZEY1ZS1mRAisvsoVw3EiOfhRM

## **LAB TASK** **2**

## Matplotlib
"""

import matplotlib.pyplot as plt

"""## Numpy"""

import numpy as np

"""## List"""

my_list = [1, 2, 3, 4, 5,6,7,8,9,10]
print(my_list)  # Output: [1, 2, 3, 4, 2, 5]

sum(my_list)

max(my_list)

min(my_list)

my_list.pop(3)

my_list.append(5)

sorted(my_list, reverse=True)

sorted(my_list)

"""## Tuple"""

my_tuple = (1, 2, 3, 4, 2)
print(my_tuple[-1])  # Output: 2
# my_tuple[1] = 5  # This will raise an error as tuples are immutable

new_list=list(my_tuple)
new_list.append(5)
new_tuple=tuple(new_list)
print(new_tuple)

"""## Set"""

set1 = {1, 2, 3, 4, 5, 6}
set2 = {4, 5, 6, 7, 8, 9}

print("Set 1:", set1)
print("Set 2:", set2)

# Union of the two sets
union_set = set1.union(set2)
print("Union:", union_set)

# Intersection of the two sets
intersection_set = set1.intersection(set2)
print("Intersection:", intersection_set)

# Difference of set1 from set2
difference_set1_set2 = set1.difference(set2)
print("Difference (set1 - set2):", difference_set1_set2)

set1.add(7)
print(set1)

set2.remove(4)
print(set2)

"""## Dictionary"""

# Difference of set2 from set1
difference_set2_set1 = set2.difference(set1)
print("Difference (set2 - set1):", difference_set2_set1)

# Example of a dictionary
my_dict = {
    "name": "Ali",
    "age": 25,
    "city": "New York",
    "email":"abc@gmail.com",
    "phone": 1234567890
}



print(my_dict)

my_dict

my_dict["country"] = "USA"
print(my_dict)